version: "2"
services:
  db:
    image: mdillon/postgis-9.5
    environment:
      POSTGRES_DB: journey-service
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    tmpfs:
      - /var/lib/postgresql/data/pgdata
